config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root to: 'homes#index'

  resources :activities, only: [:new, :create]
  resources :users, only: [:show, :index, :destroy] do
    collection do
      get 'search'
    end
  end
  resources :user_activities, only: [:new, :create]
  resources :relationships, only: [:create, :destroy]
  resources :contacts, only: [:new, :create]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_activities
  has_many :contacts

  has_many :active_relationships,  class_name: 'Relationship',
                                   foreign_key: 'follower_id',
                                   dependent: :destroy
  has_many :passive_relationships, class_name: 'Relationship',
                                   foreign_key: 'followed_id',
                                   dependent: :destroy
  has_many :following, through: :active_relationships,  source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  has_one_attached :image

  validates :user_name, presence: true, length: { maximum: 10 }

  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i
  validates_format_of :password, with: PASSWORD_REGEX, message: 'が正しくありません。アルファベットと数字の両方を入れてください'

  # ユーザーをフォローする
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # ユーザーをフォロー解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしていたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end

  # 現在のユーザーにフォローされていたらtrueを返す
  def followers?(other_user)
    followers.include?(other_user)
  end

  # ともだち判定
  def matchers
    following & followers
  end

  # ユーザー検索
  def self.search(search)
    User.where('user_name LIKE(?)', "%#{search}%") if search != ''
  end

  # ユーザー検索範囲から対象ユーザーを除く
  scope :others, ->(user) { where.not(id: user.id) }
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:user_name, :image])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(_resource)
    root_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @user_activities_today = @user.user_activities.where('created_at >= ?', Date.today).count
    @user_activities = @user.user_activities.order('user_activities.created_at DESC')

    @activity_lists = {}
    @user_activities.each do |user_activity|
      created_date = user_activity.created_at.to_date
      @activity_lists[created_date] = [] unless @activity_lists[created_date]
      @activity_lists[created_date] << user_activity
    end

    @friends = @user.matchers.take(3)
  end

  def destroy
    user_activity = UserActivity.find(params[:id])
    user_activity.destroy
    redirect_to user_path(current_user)
  end

  def index
    @friends = current_user.matchers
  end

  def search
    @search_friends = User.others(current_user).search(params[:keyword])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_accordions.html.erb
<% @activity_lists.each do |created_date, activity_list|%>
  <dl id="accordion-open">
    <dt id="accordion-open-heading-<%= created_date %>">
      <button type="button" class="flex justify-between items-center p-5 w-full font-medium text-left text-gray-900 bg-gray-100 rounded-t-xl border border-b-0 border-gray-200 focus:ring-4 focus:ring-gray-200 hover:bg-gray-100" data-accordion-target="#accordion-open-body-1" aria-expanded="true" aria-controls="accordion-open-body-1">
      <span class="flex items-center"><%= created_date.strftime('%Y年%-m月%-d日') %></span>
      <svg data-accordion-icon="" class="w-6 h-6 rotate-180 shrink-0" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
      </button>
    </dt>
    <dd id="accordion-open-body-<%= created_date %>" class="">
      <% activity_list.each do |user_activity| %>
      <div class="py-4 px-5 border-r border-l border-gray-100 text-gray-500">
        <%= user_activity.activity.activity %>
      </div>
      <% end %>
    </dd>
  </dl>
<% end %>

app/views/users/index.html.erb
<section class="bg-gray-100">
    <div class="container px-6 py-10 mx-auto">
      <div class="">
        <div class="font-semibold text-center text-yellow-900 capitalize text-base md:text-xl lg:text-3xl">
          <span class="font-semibold capitalize text-xl md:text-3xl lg:text-4xl"><%= current_user.user_name %></span>
          さんのともだちリスト
        </div>

        <div class="relative mx-auto w-60 mt-8">
            <span class="absolute inset-y-0 left-0 flex items-center pl-3">
                <svg class="w-5 h-5 text-gray-400" viewBox="0 0 24 24" fill="none">
                    <path d="M21 21L15 15M17 10C17 13.866 13.866 17 10 17C6.13401 17 3 13.866 3 10C3 6.13401 6.13401 3 10 3C13.866 3 17 6.13401 17 10Z" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path>
                </svg>
            </span>
            <%= form_with(url: search_users_path, local: true, method: :get) do |form| %>
              <%= form.text_field :keyword, placeholder: "ユーザーを探す", class: "text-xs md:text-base w-54 md:w-60 py-2 pl-10 pr-4 text-yellow-700 bg-white border rounded-md focus:border-blue-400 focus:outline-none focus:ring focus:ring-opacity-40 focus:ring-blue-300" %>
            <% end %>
        </div>
      </div>

      <div class="block md:hidden">
        <% if @friends.present? %>
        <div class="container mx-auto px-2 md:px-4 max-w-4xl">
          <div class="py-8">
            <div class="-mx-4 sm:-mx-8 px-4 sm:px-8 py-4 overflow-x-auto">
              <div class="inline-block min-w-full shadow rounded-lg overflow-hidden">
                <table class="min-w-full leading-normal">
                  <tbody>
                    <% @friends.each do |user| %>
                    <tr>
                      <td class="px-5 py-5 border-b border-gray-200 bg-white hover:bg-gray-100 coursor-pointer">
                        <%= link_to user_path(user) do %>
                          <div class="flex items-center">
                            <div class="flex-shrink-0">
                              <% unless user.image.blank? %>
                                <div>
                                  <%= image_tag user.image, class:"w-14 h-14 rounded-full inline-flex items-center justify-center object-cover block relative"%>
                                </div>
                              <% else %>
                                <div class="w-14 h-14 rounded-full inline-flex items-center justify-center bg-gray-200 text-gray-400 block relative">
                                  <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-6 h-6" viewBox="0 0 24 24">
                                    <path d="M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2"></path>
                                    <circle cx="12" cy="7" r="4"></circle>
                                  </svg>
                                </div>
                              <% end %>
                            </div>
                            <div class="ml-3">
                              <p class="text-sm md:text-base text-yellow-900 whitespace-no-wrap">
                                <%= user.user_name %>
                              </p>
                            </div>
                          </div>
                        <% end %>
                      </td>
                    </tr>
                    <% end %>
                  </tbody>

                </table>
              </div>
            </div>
          </div>
        </div>
        <% end %>
      </div>

      <div class="hidden md:block">
        <% if @friends.present? %>
        <div class="container mx-auto px-2 md:px-4 max-w-4xl">
          <div class="py-8">
            <div class="-mx-4 sm:-mx-8 px-4 sm:px-8 py-4 overflow-x-auto">
              <div class="inline-block min-w-full shadow rounded-lg overflow-hidden">
                <table class="min-w-full leading-normal">
                  <thead>
                    <tr>
                      <th scope="col" class="px-5 py-3 bg-white  border-b border-gray-200 text-yellow-900 text-left text-xs lg:text-sm font-normal text-center">
                        なまえ
                      </th>
                      <th scope="col" class="px-5 py-3 bg-white  border-b border-gray-200 text-yellow-900 text-left text-xs lg:text-sm font-normal text-center">
                        今日のアクション数
                      </th>
                      <th scope="col" class="px-5 py-3 bg-white  border-b border-gray-200 text-yellow-900 text-left text-xs lg:text-sm font-normal text-center">
                        すべてのアクション数
                      </th>
                      <th scope="col" class="px-5 py-3 bg-white  border-b border-gray-200 text-yellow-900 text-left text-sm uppercase font-normal text-center"></th>
                    </tr>
                  </thead>

                  <tbody>
                    <% @friends.each do |user| %>
                    <tr>
                      <td class="px-5 py-5 border-b border-gray-200 bg-white text-lg">
                        <div class="flex items-center">
                          <div class="flex-shrink-0">
                            <% unless user.image.blank? %>
                              <div>
                                <%= image_tag user.image, class:"w-14 h-14 rounded-full inline-flex items-center justify-center object-cover block relative"%>
                              </div>
                            <% else %>
                              <div class="w-14 h-14 rounded-full inline-flex items-center justify-center bg-gray-200 text-gray-400 block relative">
                                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-6 h-6" viewBox="0 0 24 24">
                                  <path d="M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2"></path>
                                  <circle cx="12" cy="7" r="4"></circle>
                                </svg>
                              </div>
                            <% end %>
                          </div>
                          <div class="ml-3">
                            <p class="text-sm md:text-base text-yellow-900 whitespace-no-wrap">
                              <%= user.user_name %>
                            </p>
                          </div>
                        </div>
                      </td>
                      <td class="px-5 py-5 border-b border-gray-200 bg-white text-xl text-center">
                        <p class="text-yellow-900 whitespace-no-wrap">
                          <%= user.user_activities.where('created_at >= ?', Date.today).count %>
                        </p>
                      </td>
                      <td class="px-5 py-5 border-b border-gray-200 bg-white text-xl text-center">
                        <p class="text-yellow-900 whitespace-no-wrap">
                          <%= user.user_activities.count %>
                        </p>
                      </td>
                      <td class="px-5 py-5 border-b border-gray-200 bg-white text-xl">
                        <%= link_to user_path(user) do %>
                          <span class="relative inline-block px-3 py-1 font-semibold text-yellow-900 leading-tight cursor-pointer">
                            <span aria-hidden="true" class="absolute inset-0 bg-orange-400 opacity-50 rounded-full ">
                            </span>
                              <span class="relative">
                                <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                                  <path stroke-linecap="round" stroke-linejoin="round" d="M13 5l7 7-7 7M5 5l7 7-7 7" />
                                </svg>
                              </span>
                          </span>
                        <% end %>
                      </td>
                    </tr>
                    <% end %>
                  </tbody>

                </table>
              </div>
            </div>
          </div>
        </div>
        <% end %>
      </div>

    </div>
</section>

app/views/users/search.html.erb
<section class="bg-gray-100">
    <div class="container px-6 py-10 mx-auto">
      <div class="">
        <div class="font-semibold text-center text-yellow-900 capitalize text-base md:text-xl lg:text-3xl">
          <span class="font-semibold capitalize text-xl md:text-3xl lg:text-4xl">「<%= params[:keyword] %>」</span>
          のけんさくけっか
        </div>

        <div class="relative mx-auto w-60 mt-8">
            <span class="absolute inset-y-0 left-0 flex items-center pl-3">
                <svg class="w-5 h-5 text-gray-400" viewBox="0 0 24 24" fill="none">
                    <path d="M21 21L15 15M17 10C17 13.866 13.866 17 10 17C6.13401 17 3 13.866 3 10C3 6.13401 6.13401 3 10 3C13.866 3 17 6.13401 17 10Z" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path>
                </svg>
            </span>
            <%= form_with(url: search_users_path, local: true, method: :get) do |form| %>
              <%= form.text_field :keyword, placeholder: "ユーザーを探す", class: "text-xs md:text-base w-54 md:w-60 py-2 pl-10 pr-4 text-yellow-900 bg-white border rounded-md  focus:border-blue-400 focus:outline-none focus:ring focus:ring-opacity-40 focus:ring-blue-300" %>
            <% end %>
        </div>
      </div>
      
      <% if @search_friends.present? %>
        <div class="block md:hidden">
          <div class="container mx-auto px-2 md:px-4 max-w-4xl">
            <div class="py-8">
              <div class="-mx-4 sm:-mx-8 px-4 sm:px-8 py-4 overflow-x-auto">
                <div class="inline-block min-w-full shadow rounded-lg overflow-hidden">
                  <table class="min-w-full leading-normal">
                    <tbody>
                      <% @search_friends.each do |user| %>
                      <tr>
                        <td class="px-5 py-5 border-b border-gray-200 bg-white hover:bg-gray-100 coursor-pointer">
                          <%= link_to user_path(user) do %>
                            <div class="flex items-center">
                              <div class="flex-shrink-0">
                                <% unless user.image.blank? %>
                                  <div>
                                    <%= image_tag user.image, class:"w-14 h-14 rounded-full inline-flex items-center justify-center object-cover block relative"%>
                                  </div>
                                <% else %>
                                  <div class="w-14 h-14 rounded-full inline-flex items-center justify-center bg-gray-200 text-gray-400 block relative">
                                    <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-6 h-6" viewBox="0 0 24 24">
                                      <path d="M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2"></path>
                                      <circle cx="12" cy="7" r="4"></circle>
                                    </svg>
                                  </div>
                                <% end %>
                              </div>
                              <div class="ml-3">
                                <p class="text-sm md:text-base text-yellow-900 whitespace-no-wrap">
                                  <%= user.user_name %>
                                </p>
                              </div>
                            </div>
                          <% end %>
                        </td>
                      </tr>
                      <% end %>
                    </tbody>

                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="hidden md:block">
          <div class="container mx-auto px-2 md:px-4 max-w-4xl">
            <div class="py-8">
              <div class="-mx-4 sm:-mx-8 px-4 sm:px-8 py-4 overflow-x-auto">
                <div class="inline-block min-w-full shadow rounded-lg overflow-hidden">
                  <table class="min-w-full leading-normal">
                    <thead>
                      <tr>
                        <th scope="col" class="px-5 py-3 bg-white  border-b border-gray-200 text-yellow-900 text-left text-xs lg:text-sm font-normal text-center">
                          なまえ
                        </th>
                        <th scope="col" class="px-5 py-3 bg-white  border-b border-gray-200 text-yellow-900 text-left text-xs lg:text-sm font-normal text-center">
                          今日のアクション数
                        </th>
                        <th scope="col" class="px-5 py-3 bg-white  border-b border-gray-200 text-yellow-900 text-left text-xs lg:text-sm font-normal text-center">
                          すべてのアクション数
                        </th>
                        <th scope="col" class="px-5 py-3 bg-white  border-b border-gray-200 text-yellow-900 text-left text-sm uppercase font-normal text-center"></th>
                      </tr>
                    </thead>

                    <tbody>
                      <% @search_friends.each do |user| %>
                        <tr>
                          <td class="px-5 py-5 border-b border-gray-200 bg-white text-lg">
                            <div class="flex items-center">
                              <div class="flex-shrink-0">
                                <% unless user.image.blank? %>
                                  <div>
                                    <%= image_tag user.image, class:"w-14 h-14 rounded-full inline-flex items-center justify-center object-cover block relative"%>
                                  </div>
                                <% else %>
                                  <div class="w-14 h-14 rounded-full inline-flex items-center justify-center bg-gray-200 text-gray-400 block relative">
                                    <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-6 h-6" viewBox="0 0 24 24">
                                      <path d="M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2"></path>
                                      <circle cx="12" cy="7" r="4"></circle>
                                    </svg>
                                  </div>
                                <% end %>
                              </div>
                              <div class="ml-3">
                                <p class="text-sm md:text-base text-yellow-900 whitespace-no-wrap">
                                  <%= user.user_name %>
                                </p>
                              </div>
                            </div>
                          </td>
                          <td class="px-5 py-5 border-b border-gray-200 bg-white text-xl text-center">
                            <p class="text-yellow-900 whitespace-no-wrap">
                              <%= user.user_activities.where('created_at >= ?', Date.today).count %>
                            </p>
                          </td>
                          <td class="px-5 py-5 border-b border-gray-200 bg-white text-xl text-center">
                            <p class="text-yellow-900 whitespace-no-wrap">
                              <%= user.user_activities.count %>
                            </p>
                          </td>
                          <td class="px-5 py-5 border-b border-gray-200 bg-white text-xl">
                            <%= link_to user_path(user) do %>
                              <span class="relative inline-block px-3 py-1 font-semibold text-yellow-900 leading-tight cursor-pointer">
                                <span aria-hidden="true" class="absolute inset-0 bg-yellow-400 opacity-50 rounded-full ">
                                </span>
                                  <span class="relative">
                                    <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                                      <path stroke-linecap="round" stroke-linejoin="round" d="M13 5l7 7-7 7M5 5l7 7-7 7" />
                                    </svg>
                                  </span>
                              </span>
                            <% end %>
                          </td>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% else %>
        <div class="text-sm md:text-xl mt-8 xl:mt-16 text-center">
          <p>「<b><%= params[:keyword] %></b>」に当てはまるユーザーはいませんでした。</p>
        </div>
      <% end %>
    </div>
</section>

app/views/users/show.html.erb
<section class="text-yellow-900 body-font">
  <div class="container p-5 mx-auto flex flex-col">
    <div class="lg:w-4/6 mx-auto">

      <%# ユーザー情報 %>
      <div class="flex flex-col sm:flex-row">

        <%# ユーザー情報左側、写真とボタン %>
        <div class="sm:w-1/3 sm:pr-8 sm:py-4 flex flex-col justify-center items-center text-center">
          <% unless @user.image.blank? %>
            <div>
              <%= image_tag @user.image, class:"w-36 h-36 md:w-44 md:h-44 rounded-full border-2 border-orange-200 inline-flex items-center justify-center object-cover"%>
            </div>
          <% else %>
            <div class="w-36 h-36 md:w-44 md:h-44 rounded-full border-2 border-orange-200 inline-flex items-center justify-center bg-gray-200 text-gray-400">
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-20 h-20" viewBox="0 0 24 24">
                <path d="M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2"></path>
                <circle cx="12" cy="7" r="4"></circle>
              </svg>
            </div>
          <% end %>

          <% if current_user.id == @user.id %>
            <div class="mt-0">
              <%= link_to 'アカウントせってい', edit_user_registration_path(current_user), class:"relative bg-green-400 text-yellow-900 p-3 rounded-lg text-xs md:text-sm font-semibold shadow my-4 inline-table" %>
            </div>
          <% elsif %>
            <%= render 'follow' %>
          <% end %>
        </div>

        <%# ユーザー情報右側、名前とメールアドレス %>
        <div class="sm:w-2/3 sm:pl-12 sm:pt-4 sm:border-l border-gray-200 sm:border-t-0 border-t mt-4 pt-4 sm:mt-0 text-center sm:text-left flex flex-col justify-between text-sm md:text-lg">
          <div class="flex mb-4">
            <div class="mr-4">なまえ :</div>
            <div class="border-solid border-gray-200"><%= @user.user_name %></div>
          </div>
          <% if current_user.id == @user.id %>
            <div class="flex mb-4">
              <div class="mr-4">メールアドレス :</div>
              <div class="border-solid border-gray-200"><%= @user.email %></div>
            </div>
          <% end %>
          <div class="flex mb-4">
            <div class="mr-4">今日のアクションの数 :</div>
            <div class="border-solid border-gray-200"><%= @user_activities_today %></div>
          </div>
          <div class="flex mb-4">
            <div class="mr-4">すべてのアクションの数 :</div>
            <div class="border-solid border-gray-200"><%= @user_activities.count %></div>
          </div>
          <div class="flex mb-4">
            <%= link_to users_path(@user), class:"inline-flex items-center hover:border-b border-gray-200" do %>
              <div class="mr-4">ともだち :</div>
              <span class="text-green-500">
                <%= @user.matchers.count %>
              </span>
            <% end %>
          </div>
          <div class="hidden md:block">
            <%= render 'friend_action' %>
          </div>
        </div>
      </div>

      <%# 今までのアクション ここから%>
      <div class="w-auto h-auto">
        <div class="px-4 p-10 flex justify-center">
          <h1 class="text-xl md:text-3xl ml-2 lg:ml-0 lg:text-4xl font-bold text-yellow-900 tracking-normal lg:w-11/12 text-center">今までの<span class="text-green-600">アクション</span></h1>
        </div>

        <%# アクションリストのアコーディオン %>
        <%= render partial: "actions" %>

      </div>
      <%# これまでのアクション ここまで %>

    </div>
  </div>
</section>

<script>
function accordions() {
  // クリックする要素を取得
  const parents = 'accordion-open-heading-';
	const dtObj = document.getElementsByTagName('dt');
  // 正規表現オブジェクト生成
	const dtMatch = new RegExp(parents);
  
  // for文で各要素を分解してイベント付与
  for(let i = 0; i < dtObj.length; i++) {
    if(dtObj[i].id.match(dtMatch)) {
      dtObj[i].addEventListener("click", function() {
        // hiddenにしたい要素を取得
        const children = 'accordion-open-body-';
        const ddObj = document.getElementsByTagName('dd');
        // 正規表現オブジェクト生成
        const ddMatch = new RegExp(children)
        // クラスに付与して表示切り替え
        if(ddObj[i].id.match(ddMatch)) {
          ddObj[i].classList.toggle("hidden");
        };
      });
		};
	};
};
window.addEventListener('load', accordions)

function confirmDestroy(message) {
  if (!confirm(message)) {
    return false;
  }
}

</script>