config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root to: 'homes#index'

  resources :activities, only: [:new, :create]
  resources :users, only: [:show, :index, :destroy] do
    collection do
      get 'search'
    end
  end
  resources :user_activities, only: [:new, :create]
  resources :relationships, only: [:create, :destroy]
  resources :contacts, only: [:new, :create]
end

app/models/activity.rb
class Activity < ApplicationRecord
  has_many :user_activities

  validates :activity, presence: true
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :authenticate_user!

  def new
    @user_activity = Activity.new
    @activities = Activity.all
  end

  def create
    @user_activity = UserActivity.new({ activity_id: params[:activity][:activity_id], user_id: current_user.id })
    @user_activity.save
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_lists.html.erb
<div class="px-6 xl:px-0">
    <div class="grid sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-3 pb-6 gap-8">
        <%# ごみのセクション %>
        <div role="cell" class="bg-gray-100">
            <div class="bg-white p-5 rounded-md relative h-full w-full">
                <!-- class="absolute inset-0 object-center object-cover h-full w-full"  -->
                <div class="flex">
                    <div class="text-lg md:text-2xl h-8 font-semibold text-yellow-900 m-auto mr-0 border-dotted border-green-300 lg:border-b-4">ごみ</div>
                    <%= image_tag 'separate.png', class:"w-24 h-24 md:w-32 md:h-32 m-auto" %>
                </div>
                <div class="my-5">
                    <% @activities[0,9].each do |activity| %>
                        <%= form_with model: @user_activity, path: user_activities_path, local: true do |f|%>
                            <div class="flex align-center my-7 group">
                                <%= button_tag type: 'submit', onclick: 'recordAction()' do %>
                                    <svg xmlns=”http://www.w3.org/2000/svg” class="h-6 w-6 md:h-8 md:w-8 rounded-full text-green-500 group-hover:text-white group-hover:bg-green-500"  fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"/>
                                    </svg>
                                <% end %>
                                <h4 class="text-xs md:text-base text-yellow-900 ml-4 group-hover:border-b-2 group-hover:border-green-400 group-hover:border-dotted"><%= activity.activity %></h4>
                                <%= f.hidden_field :activity_id, :value => activity.id %>
                            </div>
                        <% end %>
                    <% end %>
                </div>
            </div>
        </div>

        <%# スマートムーブのセクション %>
        <div role="cell" class="bg-gray-100">
            <div class="bg-white p-5 rounded-md relative h-full w-full">
                <!-- class="absolute inset-0 object-center object-cover h-full w-full"  -->
                <div class="flex">
                    <div class="text-base lg:text-2xl h-8 font-semibold text-yellow-900 m-auto mr-0 border-dotted border-green-300 lg:border-b-4">スマートムーブ</div>
                    <%= image_tag 'bus.png', class:"w-24 h-24 md:w-32 md:h-32 m-auto" %>
                </div>
                <div class="my-5">
                    <% @activities[10,4].each do |activity| %>
                        <%= form_with model: @user_activity, path: user_activities_path, local: true do |f|%>
                            <div class="flex align-center my-7 group">
                                <%= button_tag type: 'submit', onclick: 'recordAction()' do %>
                                    <svg xmlns=”http://www.w3.org/2000/svg” class="h-6 w-6 md:h-8 md:w-8 rounded-full text-green-500 group-hover:text-white group-hover:bg-green-500"  fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"/>
                                    </svg>
                                <% end %>
                                <h4 class="text-xs md:text-base  text-yellow-900 ml-4 group-hover:border-b-2 group-hover:border-green-400 group-hover:border-dotted"><%= activity.activity %></h4>
                                <%= f.hidden_field :activity_id, :value => activity.id %>
                            </div>
                        <% end %>
                    <% end %>
                </div>
            </div>
        </div>

        <%# 学習のセクション %>
        <div role="cell" class="bg-gray-100">
            <div class="bg-white p-5 rounded-md relative h-full w-full">
                <!-- class="absolute inset-0 object-center object-cover h-full w-full"  -->
                <div class="flex">
                    <div class="text-lg md:text-2xl h-8 font-semibold text-yellow-900 m-auto mr-0 border-dotted border-green-300 lg:border-b-4">学習</div>
                    <%= image_tag 'pc_girl.png', class:"w-24 h-24 md:w-32 md:h-32 m-auto" %>
                </div>
                <div class="my-5">
                    <% @activities[14,7].each do |activity| %>
                        <%= form_with model: @user_activity, path: user_activities_path, local: true do |f|%>
                            <div class="flex align-center my-7 group">
                                <%= button_tag type: 'submit', onclick: 'recordAction()' do %>
                                    <svg xmlns=”http://www.w3.org/2000/svg” class="h-6 w-6 md:h-8 md:w-8 rounded-full text-green-500 group-hover:text-white group-hover:bg-green-500"  fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"/>
                                    </svg>
                                <% end %>
                                <h4 class="text-xs md:text-base text-yellow-900 ml-4 group-hover:border-b-2 group-hover:border-green-400 group-hover:border-dotted"><%= activity.activity %></h4>
                                <%= f.hidden_field :activity_id, :value => activity.id %>
                            </div>
                        <% end %>
                    <% end %>
                </div>
            </div>
        </div>

        <%# 食料のセクション %>
        <div role="cell" class="bg-gray-100">
            <div class="bg-white p-5 rounded-md relative h-full w-full">
                <!-- class="absolute inset-0 object-center object-cover h-full w-full"  -->
                <div class="flex">
                    <div class="text-lg md:text-2xl h-8 font-semibold text-yellow-900 m-auto mr-0 border-dotted border-green-300 lg:border-b-4">食料</div>
                    <%= image_tag 'eating.png', class:"w-24 h-24 md:w-32 md:h-32 m-auto" %>
                </div>
                <div class="my-5">
                    <% @activities[21,2].each do |activity| %>
                        <%= form_with model: @user_activity, path: user_activities_path, local: true do |f|%>
                            <div class="flex align-center my-7 group">
                                <%= button_tag type: 'submit', onclick: 'recordAction()' do %>
                                    <svg xmlns=”http://www.w3.org/2000/svg” class="h-6 w-6 md:h-8 md:w-8 rounded-full text-green-500 group-hover:text-white group-hover:bg-green-500"  fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"/>
                                    </svg>
                                <% end %>
                                <h4 class="text-xs md:text-base text-yellow-900 ml-4 group-hover:border-b-2 group-hover:border-green-400 group-hover:border-dotted"><%= activity.activity %></h4>
                                <%= f.hidden_field :activity_id, :value => activity.id %>
                            </div>
                        <% end %>
                    <% end %>
                </div>
            </div>
        </div>

        <%# 水のセクション %>
        <div role="cell" class="bg-gray-100">
            <div class="bg-white p-5 rounded-md relative h-full w-full">
                <!-- class="absolute inset-0 object-center object-cover h-full w-full"  -->
                <div class="flex">
                    <div class="text-lg md:text-2xl h-8 font-semibold text-yellow-900 m-auto mr-0 border-dotted border-green-300 lg:border-b-4">水</div>
                    <%= image_tag 'water.png', class:"w-24 h-24 md:w-32 md:h-32 m-auto" %>
                </div>
                <div class="my-5">
                    <% @activities[23,2].each do |activity| %>
                        <%= form_with model: @user_activity, path: user_activities_path, local: true do |f|%>
                            <div class="flex align-center my-7 group">
                                <%= button_tag type: 'submit', onclick: 'recordAction()' do %>
                                    <svg xmlns=”http://www.w3.org/2000/svg” class="h-6 w-6 md:h-8 md:w-8 rounded-full text-green-500 group-hover:text-white group-hover:bg-green-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"/>
                                    </svg>
                                <% end %>
                                <h4 class="text-xs md:text-base text-yellow-900 ml-4 group-hover:border-b-2 group-hover:border-green-400 group-hover:border-dotted"><%= activity.activity %></h4>
                                <%= f.hidden_field :activity_id, :value => activity.id %>
                            </div>
                        <% end %>
                    <% end %>
                </div>
            </div>
        </div>

        <%# 電気のセクション %>
        <div role="cell" class="bg-gray-100">
            <div class="bg-white p-5 rounded-md relative h-full w-full">
                <!-- class="absolute inset-0 object-center object-cover h-full w-full"  -->
                <div class="flex">
                    <div class="text-lg md:text-2xl h-8 font-semibold text-yellow-900 m-auto mr-0 border-dotted border-green-300 lg:border-b-4">電気</div>
                    <%= image_tag 'TV.png', class:"w-24 h-24 md:w-32 md:h-32 m-auto" %>
                </div>
                <div class="my-5">
                    <% @activities[25,11].each do |activity| %>
                        <%= form_with model: @user_activity, path: user_activities_path, local: true do |f|%>
                            <div class="flex align-center my-7 group">
                                <%= button_tag type: 'submit', onclick: 'recordAction()' do %>
                                    <svg xmlns=”http://www.w3.org/2000/svg” class="h-6 w-6 md:h-8 md:w-8 rounded-full text-green-500 group-hover:text-white group-hover:bg-green-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"/>
                                    </svg>
                                <% end %>
                                <h4 class="text-xs md:text-base text-yellow-900 ml-4 group-hover:border-b-2 group-hover:border-green-400 group-hover:border-dotted"><%= activity.activity %></h4>
                                <%= f.hidden_field :activity_id, :value => activity.id %>
                            </div>
                        <% end %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/activities/new.html.erb
<!-- component -->
<div class="bg-gray-100">
    <div class="container mx-auto">
        <div role="article" class="bg-gray-100 py-8 md:py-12 md:px-8">
            <div class="px-4 pb-4 md:py-10">
                <h1 class="text-2xl md:text-3xl ml-2 lg:ml-0 lg:text-4xl font-bold text-yellow-900 tracking-normal text-center"><span class="text-green-600">アクション</span>をきろく</h1>
                <div class="text-sm md:text-lg text-yellow-900 text-center mt-8">
                    <svg xmlns=”http://www.w3.org/2000/svg” class="h-6 w-6 md:h-8 md:w-8 rounded-full text-green-500 inline"  fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"/>
                    </svg>
                    をクリックしてきろくしましょう
                </div>
            </div>
            <div class="mb-2 pr-0 md:pr-12 text-center md:text-right text-yellow-900 text-xs md:text-base">出典：環境省 こども環境白書</div>

            <%= render 'lists' %>

            <div class="text-center my-4 md:my-12 mx-6 md:mx-0 text-sm md:text-lg text-yellow-900">
                他のアクションをきろくしたい方は
                <%= link_to 'こちら', new_contact_path(current_user.id), class:"text-green-600 hover:text-green-700 font-bold hover:border-b hover:border-green-700" %>
                からリクエスト
            </div>
        </div>
    </div>
</div>

<script>
function recordAction() {
    swal({
    title: "ありがとう！",
    text: "アクションがきろくされました",
    icon: "success",
    button: "もどる",
    });
}
</script>