config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root to: 'homes#index'

  resources :activities, only: [:new, :create]
  resources :users, only: [:show, :index, :destroy] do
    collection do
      get 'search'
    end
  end
  resources :user_activities, only: [:new, :create]
  resources :relationships, only: [:create, :destroy]
  resources :contacts, only: [:new, :create]
end

app/models/activity.rb
class Activity < ApplicationRecord
  has_many :user_activities

  validates :activity, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user

  validates :name, presence: true, length: { maximum: 10 }
  validates :content, presence: true, length: { maximum: 100 }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
  validates :follower_id, presence: true, uniqueness: { scope: :followed_id }
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_activities
  has_many :contacts

  has_many :active_relationships,  class_name: 'Relationship',
                                   foreign_key: 'follower_id',
                                   dependent: :destroy
  has_many :passive_relationships, class_name: 'Relationship',
                                   foreign_key: 'followed_id',
                                   dependent: :destroy
  has_many :following, through: :active_relationships,  source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  has_one_attached :image

  validates :user_name, presence: true, length: { maximum: 10 }

  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i
  validates_format_of :password, with: PASSWORD_REGEX, message: 'が正しくありません。アルファベットと数字の両方を入れてください'

  # ユーザーをフォローする
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # ユーザーをフォロー解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしていたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end

  # 現在のユーザーにフォローされていたらtrueを返す
  def followers?(other_user)
    followers.include?(other_user)
  end

  # ともだち判定
  def matchers
    following & followers
  end

  # ユーザー検索
  def self.search(search)
    User.where('user_name LIKE(?)', "%#{search}%") if search != ''
  end

  # ユーザー検索範囲から対象ユーザーを除く
  scope :others, ->(user) { where.not(id: user.id) }
end

app/models/user_activity.rb
class UserActivity < ApplicationRecord
  belongs_to :user
  belongs_to :activity
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :authenticate_user!

  def new
    @user_activity = Activity.new
    @activities = Activity.all
  end

  def create
    @user_activity = UserActivity.new({ activity_id: params[:activity][:activity_id], user_id: current_user.id })
    @user_activity.save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :configure_account_update_params, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:user_name, :image])
  end

  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:user_name, :image])
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :authenticate_user!

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      # ContactMailer.contact_mail(@contact, current_user).deliver
      redirect_to root_path, notice: 'リクエストを送信しました'
    else
      render :new
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :content).merge(user_id: current_user.id)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @activity = Activity.order('RAND()').limit(3)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!

  def create
    @user = User.find(params[:followed_id])
    current_user.follow(@user)
    redirect_to @user, notice: 'ともだちリクエストをしました！'
  end

  def destroy
    @user = Relationship.find(params[:id]).followed
    current_user.unfollow(@user)
    redirect_to @user, notice: "#{@user}さんのともだちをやめました"
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @user_activities_today = @user.user_activities.where('created_at >= ?', Date.today).count
    @user_activities = @user.user_activities.order('user_activities.created_at DESC')

    @activity_lists = {}
    @user_activities.each do |user_activity|
      created_date = user_activity.created_at.to_date
      @activity_lists[created_date] = [] unless @activity_lists[created_date]
      @activity_lists[created_date] << user_activity
    end

    @friends = @user.matchers.take(3)
  end

  def destroy
    user_activity = UserActivity.find(params[:id])
    user_activity.destroy
    redirect_to user_path(current_user)
  end

  def index
    @friends = current_user.matchers
  end

  def search
    @search_friends = User.others(current_user).search(params[:keyword])
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>EAction</title>
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <%= favicon_link_tag('favicon.ico') %>
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>
        <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

        <%= stylesheet_link_tag "application" %>
        <%= javascript_importmap_tags %>
        <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    </head>

    <body class="bg-amber-50">
        <header>
            <nav class="bg-green-400 shadow fixed w-screen top-0 z-10 border-b-2 border-white">
                <div class="container py-1 mx-auto md:flex">
                    <div class="flex items-center justify-between ml-4 md:ml-8">
                        <%= link_to image_tag("logo_image.png", class:"m-0 p-0 w-1/4 md:w-44"), root_path %>
                        
                        <%# <!-- Mobile menu button --> ハンバーガーメニュー %>
                        <div class="flex md:hidden mr-4" id="menu-btn">
                            <button type="button" class="text-yellow-800 hover:text-yellow-900 focus:outline-none hover-pointer" aria-label="toggle menu">
                                <svg viewBox="0 0 24 24" class="w-6 h-6 fill-current">
                                    <path fill-rule="evenodd" d="M4 5h16a1 1 0 0 1 0 2H4a1 1 0 1 1 0-2zm0 6h16a1 1 0 0 1 0 2H4a1 1 0 0 1 0-2zm0 6h16a1 1 0 0 1 0 2H4a1 1 0 0 1 0-2z"></path>
                                </svg>
                            </button>
                        </div>
                    </div>

                    <!-- Mobile Menu open: "block", Menu closed: "hidden" -->
                    <div class="w-full md:flex md:items-center md:justify-end pt-4 hidden mr-8 text-xs lg:text-sm" id="menu">
                        <div class="flex flex-col px-6 py-3 mx-4 md:flex-row md:mx-0 md:py-0">
                            <% if user_signed_in? %>
                                <%= link_to '今日のアクション', root_path(anchor: 'today-action'), class:"px-2 py-1 font-medium text-yellow-900 transition-colors duration-200 transform rounded hover:bg-yellow-900 hover:text-gray-100 lg:mx-2" %>
                                <%= link_to 'アクションをきろく', new_activity_path, class:"px-2 py-1 font-medium text-yellow-900 transition-colors duration-200 transform rounded hover:bg-yellow-900 hover:text-gray-100 md:mx-2" %>
                                <%= link_to 'マイページ', user_path(current_user.id), class:"px-2 py-1 font-medium text-yellow-900 transition-colors duration-200 transform rounded hover:bg-yellow-900 hover:text-gray-100 md:mx-2", data: { turbo: false } %>
                                <%= link_to 'あそびかた', root_path(anchor: 'howtoplay'), class:"px-2 py-1 font-medium text-yellow-900 transition-colors duration-200 transform rounded hover:bg-yellow-900 hover:text-gray-100 md:mx-2" %>
                                <%= button_to 'ログアウト', destroy_user_session_path, method: :delete, class:"px-2 py-1 font-medium text-yellow-900 transition-colors duration-200 transform rounded hover:bg-yellow-900 hover:text-gray-100 md:mx-2" %>
                            <% else %>
                                <%= link_to 'あそびかた', root_path(anchor: 'howtoplay'), class:"px-2 py-1 font-medium text-yellow-900 transition-colors duration-200 transform rounded hover:bg-yellow-900 hover:text-gray-100 md:mx-2" %>
                                <%= link_to '新しくはじめる', new_user_registration_path, class:"px-2 py-1 font-medium text-yellow-900 transition-colors duration-200 transform rounded hover:bg-yellow-900 hover:text-gray-100 md:mx-2" %>
                                <%= link_to 'ログイン', new_user_session_path, class:"px-2 py-1 font-medium text-yellow-900 transition-colors duration-200 transform rounded hover:bg-yellow-900 hover:text-gray-100 md:mx-2" %>
                            <% end %>
                        </div>
                    </div>
                </div>
            </nav>
        </header>
        <main class="container mx-auto px-12 mt-8 pt-12 md:pt-24 justify-center">
            <%= yield %>
        </main>
        <script>
            function pullDown() {
            const pullDownList = document.getElementById("menu-btn");
            pullDownList.addEventListener('click', function() {
                const contents = document.getElementById("menu");
                contents.classList.toggle("hidden");
            })
            };

            window.addEventListener('load', pullDown)
        </script>
    </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="px-4 pb-4 ml-2 text-rose-600 text-xs md:text-base">
  <ul class="list-disc">
    <% model.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>